
name: CD

on:
  workflow_dispatch:
jobs:
  delivery:
    runs-on: ubuntu-latest
    env:
      HOST_DELIVERY: ${{ secrets.HOST_DELIVERY }}
      USER_DELIVERY: ${{ secrets.USER_DELIVERY }}
      KEY_DELIVERY: ${{ secrets.KEY_DELIVERY }}
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: .github/scripts/deploy.sh
