
name: CD

on:
  workflow_dispatch:
jobs:
  delivery:
    runs-on: ubuntu-latest
    env:
      HOST_DELIVERY: ${{ secrets.HOST_DELIVERY }}
      USER_DELIVERY: ${{ secrets.USER_DELIVERY }}
      KEY_DELIVERY: ${{ secrets.KEY_DELIVERY }}

    steps:
    - uses: actions/checkout@v2
    - name: create env file
      run: |
          touch .env
          echo HOST_DELIVERY=${{ secrets.HOST_DELIVERY }} >> .env
          echo USER_DELIVERY=${{ secrets.USER_DELIVERY }} >> .env
          echo KEY_DELIVERY=${{ secrets.KEY_DELIVERY }} >> .env
          echo PATH_DELIVERY=${{ secrets.PATH_DELIVERY }} >> .env
          echo SCRIPT_NAME=deploy.sh >> .env
          cat .env
    - name: Run a one-line script
      run: docker-compose up 
