
name: CD

on:
  workflow_dispatch:
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: bash -eux $GITHUB_WORKSPACE/scripts/deploy.sh
